MattWebsite/Posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

MattWebsite/Main/routes.py
from flask import render_template, request, Blueprint, url_for
from flask_login import current_user
from MattWebsite.models import Post

main = Blueprint('main', __name__)

@main.route('/')
def index():
    return render_template('index.html', _external=True)

@main.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    image_file = url_for('static', filename='ProfilesPhotos/' + current_user.image_file)
    return render_template('home.html', posts=posts, image_file=image_file)

MattWebsite/Posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from MattWebsite import db
from MattWebsite.models import Post
from MattWebsite.Posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    image_file = url_for('static', filename='ProfilesPhotos/' + current_user.image_file)
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('users.profile'))
    return render_template('create_post.html', form=form, image_file=image_file)

@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    image_file = url_for('static', filename='ProfilesPhotos/' + current_user.image_file)
    return render_template('post.html', post=post, image_file=image_file)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method =='GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', form=form)

@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')

    return render_template('profile.html')

MattWebsite/Users/routes.py
from flask import render_template, redirect, url_for, flash, request, Blueprint
from flask_login import login_user, login_required, current_user, logout_user
from MattWebsite import db, bcrypt
from MattWebsite.models import User, Post
from MattWebsite.Users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from MattWebsite.Users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)

@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash(f'Welcome back {user.username}!', 'success')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unseccessful. Please check username and password.', 'danger')
    return render_template('login.html', form=form)

@users.route('/signup', methods=['GET', 'POST'])
def signup():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Account created for {form.username.data}!', 'success')
        return redirect(url_for('users.login'))
    return render_template('signup.html', form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    posts = current_user.posts
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='ProfilesPhotos/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form, posts=posts)

@users.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    posts = current_user.posts
    image_file = url_for('static', filename='ProfilesPhotos/' + current_user.image_file)
    return render_template('Profile.html', image_file=image_file, posts=posts)

@users.route("/user/<string:username>")
def user_post(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    image_file = url_for('static', filename='ProfilesPhotos/' + current_user.image_file)
    return render_template('user_posts.html', posts=posts, user=user, image_file=image_file)

@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        print('hola')
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash("An email has been sent with instructions to reset your password.", "alert-info")
        return redirect(url_for('main.login'))

    return render_template('reset_request.html', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', "alert-info")
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been updated!', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', form=form)

MattWebsite/templates/Profile.html
{% extends 'base.html' %}

{% block head %}
<!--Website Title-->
<title>Profile</title>
<!--link-->
<link rel="stylesheet" type="text/css" href="{{ url_for('static' , filename='css/profile.css') }}">
{% endblock %}

{% block body %} 

    
<div class="content">
    <aside class="profileCard">
        <figure>
            <div class="avatar">
                <img src="{{ image_file }}" class="avatar_image">
            </div>
            <figcaption>{{ current_user.username }}</figcaption>
        </figure>
        <nav>
            <ul> 
                <li id="t-mrg-0">Name: {{ current_user.username }}</li>
                <li>Age: {{ current_user.age }}</li>
                <li>Bio: {{current_user.bio }}</li>
                <li class="Update-Account"><a href="{{ url_for('users.account') }}">Update Account</a></li>
            </ul>
        </nav>
    </aside>
    <main class="postSection" id="scrollbar">
        {% for post in posts %}
        <div class="post">
            <h4 class="title-post"><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h4>
            <small class="author-post">{{ post.author.username }} {{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            <p>
                {{ post.content }}
            </p>
        </div>
        {% endfor %}
    </main>
</div>
        

{% endblock %}

MattWebsite/templates/account.html
{% extends 'base.html' %}

{% block head %}
<!--Website Title-->
<title>Molletes</title>
<!--link-->
<link rel="stylesheet" type="text/css" href="{{ url_for('static' , filename='css/account.css') }}">
{% endblock %}

{% block body %} 

<div class="content">
    <aside class="profileCard">
        <figure>
            <div class="avatar">
                <img src="{{ image_file }}" class="avatar_image">
            </div>
            <figcaption>{{ current_user.username }}</figcaption>
        </figure>
        <form class="loginBox" method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
                  
            {% if form.username.errors %}
                {{ form.username(class="textbox-invalid", placeholder="username") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.username(class="textbox", placeholder="username") }}
            {% endif %}

            {% if form.email.errors %}
                {{ form.email(class="textbox-invalid", placeholder="Email") }}
                    <div class="invalid-feedback">
                {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
                </div>
            {% else %}
                {{ form.email(class="textbox", placeholder="Email") }}
            {% endif %}

            {{ form.picture.label(class="label") }}
            {{ form.picture(class="picture_formbox") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="invalid-feedback">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}

            {{ form.submit(class="button", id="l-mrg-1r") }}
        </form>
    </aside>
    <main class="postSection" id="scrollbar">
        {% for post in posts %}
        <div class="post">
            <h4 class="title-post"><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h4>
            <small class="author-post">{{ post.author.username }} {{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            <p>
                {{ post.content }}
            </p>
        </div>
        {% endfor %}
    </main>
</div>

{% endblock %}

MattWebsite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Font-->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static' , filename='css/base.css') }}">
    <!-- FLashed messages are declared here and appear at the top of the page  -->
    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            {% for category, message in messages %}
            <div class="alert-{{ category }}">
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}    
    {% endwith %}
    {% block head %}{% endblock %}
</head>
<body>

    <header>
        <h1 class="logo">Website</h1>
        <nav> 
            <ul class="nav_links">
                {% if current_user.is_authenticated %}
                <!-- This is where all the post will be  -->
                <li><a href="{{ url_for('main.home') }}">Home</a></li>
                <!-- Write a post, the links beneath this only works only if you are logged in  -->
                <li><a href="{{ url_for('posts.new_post') }}">Write</a></li>
                <!-- Look at your profile  -->
                <li><a href="{{ url_for('users.profile') }}">Profile</a></li>
                <!-- Logout  -->
                <li><a href="{{ url_for('users.logout') }}">Logout</a></li>
                {% else %}
                <!-- This is where all the post will be  -->
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
                <!-- Log in  -->
                <li><a href="{{ url_for('users.login') }}">Login</a></li>
                <!-- If you dont have an account Sign up  -->
                <li><a href="{{ url_for('users.signup') }}">Sign up</a></li>
                {% endif %}
            </ul>
        </nav>
        <!-- Contact us  -->
        <button class="button">Contact</button>
    </header>

    {% block body %}{% endblock %}

    <footer>
        Hello
    </footer>
</body>
</html>

MattWebsite/templates/create_post.html
{% extends 'base.html' %}

{% block head %}
<!--Website Title-->
<title>Profile</title>
<!--link-->
<link rel="stylesheet" type="text/css" href="{{ url_for('static' , filename='css/write.css') }}">
{% endblock %}

{% block body %} 

    
<div class="content">
    <aside class="profileCard">
        <figure>
            <div class="avatar">
                <img src="{{ image_file }}" class="avatar_image">
            </div>
            <figcaption>{{ current_user.username }}</figcaption>
        </figure>
        <nav>
            <ul> 
                <li id="t-mrg-0">Name: {{ current_user.username }}</li>
                <li>Age: </li>
                <li>Bio: </li>
                <li class="Update-Account"><a href="{{ url_for('users.account') }}">Update Account</a></li>
            </ul>
        </nav>
    </aside>
    <main class="postSection" id="scrollbar">
        <div class="post">

            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <div class="form-post-title">
                    {% if form.title.errors %}
                        {{ form.title(class="textbox-invalid", placeholder="Title") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="textbox-title-post", placeholder="Title") }}
                    {% endif %}
                </div>
                
        
                <div class="form-post-content">
                    {% if form.content.errors %}
                        {{ form.content(class="textbox-invalid", placeholder="Content") }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class="textbox-content-post", placeholder="Content") }}
                    {% endif %}
                </div>
            
                <div class="from-post-button">
                    {{ form.submit(class="button") }}
                </div>
            </form>
        </div>
    </main>
</div>

{% endblock %}

MattWebsite/templates/home.html
{% extends 'base.html' %}

{% block head %}
<!--Website Title-->
<title>Home</title>
<!--link-->
<link rel="stylesheet" type="text/css" href="{{ url_for('static' , filename='css/profile.css') }}">
{% endblock %}

{% block body %} 

    
<div class="content">
    <aside class="profileCard">
        <figure>
            <div class="avatar">
                <img src="{{ image_file }}" class="avatar_image">
            </div>
            <figcaption>{{ current_user.username }}</figcaption>
        </figure>
        <nav>
            <ul> 
                <li id="t-mrg-0">Name: {{ current_user.username }}</li>
                <li>Age: {{ current_user.age }}</li>
                <li>Bio: {{current_user.bio }}</li>
                <li class="Update-Account"><a href="{{ url_for('users.account') }}">Update Account</a></li>
            </ul>
        </nav>
    </aside>
    <main class="postSection" id="scrollbar">
        {% for post in posts.items %}
        <div class="post">
            <h3 class="title-post"><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h3>
            <small class="author-post"><a href="{{ url_for('users.user_post', username=post.author.username) }}">{{ post.author.username }} {{ post.date_posted.strftime('%Y-%m-%d') }}</a></small>
            <p>
                {{ post.content }}
            </p>
        </div>
        {% endfor %}
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if posts.page == page_num %}
                    <a style="color: red; text-decoration: none;" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a style="color: green; text-decoration: none;" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>

                {% endif %}

            {% else %}
                ...
            {% endif %}
        {% endfor %}
    </main>
</div>
        

{% endblock %}

MattWebsite/templates/index.html
{% extends 'base.html' %}

{% block head %}
<!--Website Title-->
<title>Molletes</title>
<!--link-->
<link rel="stylesheet" type="text/css" href="{{ url_for('static' , filename='css/index.css') }}">
{% endblock %}

{% block body %} 


<section id="mainContent">
    <div class="container"><a href="{{ url_for('users.profile') }}"><img src="{{ url_for('static' , filename='Images/lol1.jpg') }}" alt=""></a></div>
    <div class="container"><a href=""><img src="{{ url_for('static' , filename='Images/lol2.jpg') }}" alt=""></a></div>
    <div class="container"><a href=""><img src="{{ url_for('static' , filename='Images/lol3.jpg') }}" alt=""></a></div>
</section>

{% endblock %}

MattWebsite/templates/login.html
{% extends 'base.html' %}

{% block head %}
<!--Website Title-->
<title>Login</title>
<!--link-->
<link rel="stylesheet" type="text/css" href="{{ url_for('static' , filename='css/signup_login.css') }}">
{% endblock %}

{% block body %} 


<form class="loginBox" method="POST" action="">
    {{ form.hidden_tag() }}
          
    {% if form.email.errors %}
        {{ form.email(class="textbox-invalid", placeholder="Email") }}
        <div class="invalid-feedback">
            {% for error in form.email.errors %}
                <span>{{ error }}</span>
            {% endfor %}
        </div>
    {% else %}
        {{ form.email(class="textbox", placeholder="Email") }}
    {% endif %}

            
    {% if form.password.errors %}
        {{ form.password(class="textbox-invalid", placeholder="Password") }}
        <div class="invalid-feedback">
            {% for error in form.password.errors %}
                <span>{{ error }}</span>
            {% endfor %}
        </div>
    {% else %}
        {{ form.password(class="textbox", placeholder="Password") }}
    {% endif %}

    <div class="rememberMe">
        {{ form.remember(class="rememberBox") }} 
        {{ form.remember.label(class="rememberLabel") }}

    </div>


    {{ form.submit(class="button") }}

    <small class="legend">
        <a href="{{ url_for('users.reset_request') }}">Forgot your password?</a>
    </small>
</form>


{% endblock %}

MattWebsite/templates/post.html
{% extends 'base.html' %}

{% block head %}
<!--Website Title-->
<title>Profile</title>
<!--link-->
<link rel="stylesheet" type="text/css" href="{{ url_for('static' , filename='css/profile.css') }}">
<style>
    #dlt_btn{
        background-color:  #FE5F55;
        margin-right: 0;
        font-size: 10px;
        padding: 9px;
        text-decoration: none;
        color: black;
        margin-top: 1rem;
    }
    #Update_btn{
        background-color:  #4C4C47;
        margin-right: 0;
        font-size: 9.5px;
        padding: 9px;
        text-decoration: none;
        color: black;
    }
    p{
        width:100%;
        word-wrap: break-word;
        margin-bottom: 10px;
    }
</style>
{% endblock %}

{% block body %} 

    
<div class="content">
    <aside class="profileCard">
        <figure>
            <div class="avatar">
                <img src="{{ image_file }}" class="avatar_image">
            </div>
            <figcaption>{{ current_user.username }}</figcaption>
        </figure>
        <nav>
            <ul> 
                <li id="t-mrg-0">Name: {{ current_user.username }}</li>
                <li>Age: {{ current_user.age }}</li>
                <li>Bio: {{current_user.bio }}</li>
                <li class="Update-Account"><a href="{{ url_for('users.account') }}">Update Account</a></li>
            </ul>
        </nav>
    </aside>
    <main class="postSection" id="scrollbar">
        <div class="post">
            <h4 class="title-post">{{ post.title }}</h4>
            <small class="author-post">{{ post.author.username }} {{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            <p>
                {{ post.content }}
            </p>
            {% if post.author == current_user %}
                <a href="{{url_for('posts.update_post', post_id=post.id)}}" class="button" id="Update_btn">Update Post</a>
                <!-- <a href="#" class="button" id="dlt_btn" data-toggle="modal" data-target="#Modal">Delete Post</a> -->
                <form action="{{url_for('posts.delete_post', post_id=post.id)}}" method="POST">
                    <input class="button" id="dlt_btn" type="submit" value="Delete Post">
                </form>
            {% endif %}
        </div>
    </main>
</div>
        

{% endblock %}

MattWebsite/templates/reset_request.html
{% extends 'base.html' %}

{% block head %}
<!--Website Title-->
<title>Reset Request</title>
<!--link-->
<link rel="stylesheet" type="text/css" href="{{ url_for('static' , filename='css/signup_login.css') }}">
{% endblock %}

{% block body %} 


<form class="loginBox" method="POST" action="">
    {{ form.hidden_tag() }}
          
    {% if form.email.errors %}
        {{ form.email(class="textbox-invalid", placeholder="Email") }}
        <div class="invalid-feedback">
            {% for error in form.email.errors %}
                <span>{{ error }}</span>
            {% endfor %}
        </div>
    {% else %}
        {{ form.email(class="textbox", placeholder="Email") }}
    {% endif %}

    {{ form.submit(class="button") }}
</form>


{% endblock %}

MattWebsite/templates/reset_token.html
<!--Website Title-->
<title>Reset Password</title>
<!--link-->
<link rel="stylesheet" type="text/css" href="{{ url_for('static' , filename='css/signup_login.css') }}">
{% endblock %}

{% block body %} 


<form class="loginBox" method="POST" action="">
    {{ form.hidden_tag() }}
          
    {% if form.password.errors %}
        {{ form.password(class="textbox-invalid", placeholder="password") }}
        <div class="invalid-feedback">
            {% for error in form.password.errors %}
                <span>{{ error }}</span>
            {% endfor %}
        </div>
    {% else %}
        {{ form.password(class="textbox", placeholder="password") }}
    {% endif %}

    {% if form.confirm_password.errors %}
        {{ form.confirm_password(class="textbox-invalid", placeholder="Confirm Email") }}
        <div class="invalid-feedback">
            {% for error in form.confirm_password.errors %}
                <span>{{ error }}</span>
            {% endfor %}
        </div>
    {% else %}
        {{ form.confirm_password(class="textbox", placeholder="Confirm Password") }}
    {% endif %}

    {{ form.submit(class="button") }}
</form>


{% endblock %}

MattWebsite/templates/signup.html
{% extends 'base.html' %}

{% block head %}
<!--Website Title-->
<title>Sign up</title>
<!--link-->
<link rel="stylesheet" type="text/css" href="{{ url_for('static' , filename='css/signup_login.css') }}">
{% endblock %}

{% block body %} 


<form class="loginBox" method="POST" action="">
    {{ form.hidden_tag() }}

    {% if form.username.errors %}
        {{ form.username(class="textbox-invalid", placeholder="Username") }}
        <div class="invalid-feedback">
            {% for error in form.username.errors %}
                <span>{{ error }}</span>
            {% endfor %}
        </div>
    {% else %}
        {{ form.username(class="textbox", placeholder="Username") }}
    {% endif %}

        
    {% if form.email.errors %}
        {{ form.email(class="textbox-invalid", placeholder="Email") }}
        <div class="invalid-feedback">
            {% for error in form.email.errors %}
                <span>{{ error }}</span>
            {% endfor %}
        </div>
    {% else %}
        {{ form.email(class="textbox", placeholder="Email") }}
    {% endif %}

        
    {% if form.password.errors %}
        {{ form.password(class="textbox-invalid", placeholder="Password") }}
        <div class="invalid-feedback">
            {% for error in form.password.errors %}
                <span>{{ error }}</span>
            {% endfor %}
        </div>
    {% else %}
        {{ form.password(class="textbox", placeholder="Password") }}
    {% endif %}


    {% if form.confirm_password.errors %}
        {{ form.confirm_password(class="textbox-invalid", placeholder="Confirm Email") }}
        <div class="invalid-feedback">
            {% for error in form.confirm_password.errors %}
                <span>{{ error }}</span>
            {% endfor %}
        </div>
    {% else %}
        {{ form.confirm_password(class="textbox", placeholder="Confirm Password") }}
    {% endif %}

    {{ form.submit(class="button") }}
    <small class="legend">
        Already have an account? <a href="{{ url_for('users.login') }}"> Log in</a>
    </small>
</form>


{% endblock %}

MattWebsite/templates/user_posts.html
{% extends 'base.html' %}

{% block head %}
<!--Website Title-->
<title>Home</title>
<!--link-->
<link rel="stylesheet" type="text/css" href="{{ url_for('static' , filename='css/profile.css') }}">
{% endblock %}

{% block body %} 

    
<div class="content">
    <aside class="profileCard">
        <figure>
            <div class="avatar">
                <img src="{{ image_file }}" class="avatar_image">
            </div>
            <figcaption>{{ user.username }}</figcaption>
        </figure>
        <nav>
            <ul> 
                <li id="t-mrg-0">Name: {{ user.name }}</li>
                <li>Age: {{ user.age }}</li>
                <li>Bio: {{ user.bio }}</li>
            </ul>
        </nav>
    </aside>
    <main class="postSection" id="scrollbar">
        {% for post in posts.items %}
        <div class="post">
            <h4 class="title-post"><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h4>
            <small class="author-post">{{ post.author.username }} {{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            <p>
                {{ post.content }}
            </p>
        </div>
        {% endfor %}
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if posts.page == page_num %}
                    <a style="color: red; text-decoration: none;" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a style="color: green; text-decoration: none;" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>

                {% endif %}

            {% else %}
                ...
            {% endif %}
        {% endfor %}
    </main>
</div>
        

{% endblock %}

MattWebsite/templates/write.html
{% extends 'base.html' %}

{% block head %}
<!--Website Title-->
<title>Profile</title>
<!--link-->
<link rel="stylesheet" type="text/css" href="{{ url_for('static' , filename='css/write.css') }}">
{% endblock %}

{% block body %} 

    
<div class="content">
    <aside class="profileCard">
        <figure>
            <div class="avatar">
                <img src="{{ image_file }}" class="avatar_image">
            </div>
            <figcaption>{{ current_user.username }}</figcaption>
        </figure>
        <nav>
            <ul> 
                <li id="t-mrg-0">Name: {{ current_user.name }}</li>
                <li>Age: {{ current_user.age }}</li>
                <li>Bio: {{ current_user.bio }}</li>
                <li class="Update-Account"><a href="{{ url_for('users.account') }}">Update Account</a></li>
            </ul>
        </nav>
    </aside>
    <main class="postSection" id="scrollbar">
        <div class="post">
            <h4 class="title-post">Title</h4>
            <small class="author-post"> Author</small>
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores officia iusto quibusdam? Ullam voluptatibus praesentium nisi quasi in dicta necessitatibus magni quod, molestias blanditiis consequuntur accusantium soluta repudiandae veniam perspiciatis dolores quaerat molestiae alias laudantium reiciendis, ipsum illo quo optio. Natus blanditiis voluptas fugiat recusandae ducimus et aliquam cumque non, nam quos similique maiores voluptate fugit delectus, quidem magni quasi ad officia harum atque eos rerum fuga beatae autem. Quos minima quam, corrupti beatae maiores similique tenetur cupiditate nulla vitae qui necessitatibus inventore delectus consequuntur alias reiciendis? Consequuntur et maiores, illo itaque facilis cupiditate, adipisci porro, magni iste rerum odio?
            </p>
        </div>
    </main>
</div>
        

{% endblock %}